adding nearby touristic places method
CampusDual/2023-BBE-1-G2 pull request #39
Opened 2023-07-10 10:10 UTC by AntonioCrespo2605

2023-07-10 11:59 UTC, cesarsantiagonunez requested changes

2023-07-10 11:59 UTC, cesarsantiagonunez commented on jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
> +        String formattedLatitude = String.valueOf(latitude);
movede este metodo o service ainda que non fagades ningunha chamada a base de datos

2023-07-10 11:59 UTC, cesarsantiagonunez commented on jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
> +        private double longitude;
creade unha clase nova separada para esto podedes metela nun paquete novo entity

2023-07-10 11:59 UTC, cesarsantiagonunez commented on jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
> +        List<TouristicPlace> touristicPlaces = new ArrayList<>();
movede este metodo e o seguinte a clase TouristicPlace

2023-07-10 11:59 UTC, cesarsantiagonunez commented on jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
> +        HttpURLConnection connection = (HttpURLConnection) new URL(requestUrl).openConnection();
esta e unha forma de facelo, botadelle un ollo a como seria facendoo con HttpClient e decidide que vos parece mellor https://www.baeldung.com/httpclient-post-http-request

2023-07-12 07:39 UTC, closed without merging

2023-07-12 07:39 UTC, AntonioCrespo2605 commented
.